services:

  db:
    image: mysql
    restart: always
    container_name: teste-main-db
    environment:
        MYSQL_DATABASE: 'db'
        MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
        - ./data/db:/var/lib/mysql

